import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  let smthngin = 1 + 1;

  /* debugger; */

  smthngin++;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App11</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">Hello world {smthngin}</h1>
    </div>
  );
};

export default Home;
